version: 2
jobs:
  "test":
    docker:
      - image: docker.io/golang:1.14.0
    steps:
      - checkout
      - run:
          name: Test
          command: make test
  "images":
    docker:
      - image: docker:stable
    steps:
      - attach_workspace:
          at: /
      - checkout
      - setup_remote_docker
      - run:
          name: Prepare env
          command: |
            echo ${DOCKERHUB_SECRET} | docker login -u ${DOCKERHUB_USER} --password-stdin
            apk update
            apk add make bash git
      - run:
          name: Build all the docker images
          command: make GIT_BRANCH=master image/all
      - run:
          name: Push images
          command: |
            make GIT_BRANCH=master push/builder
            make GIT_BRANCH=master push/driverkit
      - run:
          name: Push latest images
          command: make push/latest
  "release":
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Prepare env
          command: |
            echo ${DOCKERHUB_SECRET} | docker login -u ${DOCKERHUB_USER} --password-stdin
      - run:
          name: Install goreleaser
          command: |
            curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
      - run:
          name: Release binary
          command: |
            make release
      - run:
          name: Release image
          command: |
            make release/image
workflows:
  version: 2
  build:
    jobs:
      - "test":
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - "images":
          context: falco
          filters:
            branches:
              only:
                - master
          requires:
            - "test"
      - "release":
          context: falco
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
          requires:
            - test
